# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb8d5972f989c7c281fbd58111521ed4595d3a41379ec3463630d16d00a16c4e83ebd790f4b237d8ac2db28f67f92c30db30fc76a6efbfa7f4152a154bacedd7

test:
  secret_key_base: 21b7a25a2da55306f0348e59b9fb7400c64aef3754b8f84d0020f28bede07deb02e069e296c022e5a8041381b986af832cb2a3de3e38e9835c804382b5a2235e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
